spring:
  application:
    name: to_do_list
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost/to_do_list
      username: postgres
      password: 12345678
    server:
      port: 5432