spring:
  application:
    name: to_do_list
    server:
      port: 5432

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/to_do_list
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect